# Generated by Django 4.2.4 on 2023-08-10 09:38

import app1.manager
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrimony_id', models.CharField(max_length=10, unique=True)),
                ('matrimony_profile_for', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Professional_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_education', models.CharField(max_length=50)),
                ('employed_in', models.CharField(choices=[('Government', 'Government'), ('Private', 'Private'), ('Business', 'Business'), ('Defence', 'Defence'), ('Self Employed', 'Self Employed'), ('Not Working', 'Not Working')], max_length=30)),
                ('annual_income', models.CharField(choices=[('below_1_lakh', 'Below 1 lakh'), ('1_to_2_lakh', '1 - 2 lakh'), ('2_to_3_lakh', '2 - 3 lakh'), ('3_to_4_lakh', '3 - 4 lakh'), ('4_to_5_lakh', '4 - 5 lakh'), ('5_to_6_lakh', '5 - 6 lakh'), ('6_to_7_lakh', '6 - 7 lakh'), ('7_to_8_lakh', '7 - 8 lakh'), ('8_to_9_lakh', '8 - 9 lakh'), ('9_to_10_lakh', '9 - 10 lakh'), ('above_10_lakh', 'Above 10 lakh')], max_length=30)),
                ('work_location', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_details_profile', to='app1.member')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(choices=[('Never married', 'Never married'), ('Divorced', 'Divorced')], max_length=15)),
                ('height', models.CharField(max_length=20)),
                ('family_status', models.CharField(choices=[('Middle class', 'Middle class'), ('Upper Middle Class', 'Upper Middle Class'), ('Rich', 'Rich')], max_length=30)),
                ('family_type', models.CharField(choices=[('Joint', 'Joint'), ('Nuclear', 'Nuclear')], max_length=30)),
                ('family_values', models.CharField(choices=[('Orthodox', 'Orthodox'), ('Traditional', 'Traditional'), ('Moderate', 'Moderate'), ('Liberal', 'Liberal')], max_length=30)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_details_profile', to='app1.member')),
            ],
        ),
        migrations.CreateModel(
            name='Basic_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_of_birth', models.DateField()),
                ('religion', models.CharField(max_length=30)),
                ('mother_tongue', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='basic_details_groups', to='auth.group', verbose_name='groups')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basic_details_profile', to='app1.member')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='basic_details_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', app1.manager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_you', models.CharField(max_length=200)),
                ('member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_profile', to='app1.member')),
            ],
        ),
    ]
