# Generated by Django 4.2.4 on 2023-08-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional_details',
            name='occupation',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='family_status',
            field=models.CharField(choices=[('Upper Middle Class', 'Upper Middle Class'), ('Middle Class', 'Middle Class'), ('Rich', 'Rich')], max_length=30),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='marital_status',
            field=models.CharField(choices=[('Never Married', 'Never Married'), ('Married', 'Married')], max_length=15),
        ),
    ]
