# Generated by Django 4.2.4 on 2023-08-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_professional_details_occupation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional_details',
            name='annual_income',
            field=models.CharField(choices=[('below_1_lakh', 'Below 1 lakh'), ('1 - 2 lakh', '1 - 2 lakh'), ('2 - 3 lakh', '2 - 3 lakh'), ('3 - 4 lakh', '3 - 4 lakh'), ('4 - 5 lakh', '4 - 5 lakh'), ('5 - 6 lakh', '5 - 6 lakh'), ('6 - 7 lakh', '6 - 7 lakh'), ('7 - 8 lakh', '7 - 8 lakh'), ('8 - 9 lakh', '8 - 9 lakh'), ('9 - 10 lakh', '9 - 10 lakh'), ('Above 10 lakh', 'Above 10 lakh')], max_length=30),
        ),
    ]
