# Generated by Django 4.2.4 on 2023-08-28 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range_min', models.IntegerField()),
                ('age_range_max', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=20)),
                ('eye_color', models.CharField(max_length=20)),
                ('skin_tone', models.CharField(max_length=20)),
                ('body_type', models.CharField(max_length=20)),
                ('hobbies', models.CharField(max_length=200)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='app1.member')),
            ],
        ),
    ]
