# Generated by Django 4.2.4 on 2023-08-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('plan_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_period', models.PositiveIntegerField()),
            ],
        ),
    ]
