# Generated by Django 4.2.4 on 2023-09-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_membershippackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_details',
            name='is_diamond',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basic_details',
            name='is_gold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basic_details',
            name='is_platinum',
            field=models.BooleanField(default=False),
        ),
    ]
