# Generated by Django 4.2.1 on 2023-09-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basic_details',
            old_name='email_id',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='marital_status',
            field=models.CharField(choices=[('Never Married', 'Never Married'), ('Divorced', 'Divorced')], max_length=15),
        ),
    ]
