# Generated by Django 4.2.1 on 2023-09-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_rename_email_id_basic_details_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic_details',
            name='is_diamond',
        ),
        migrations.RemoveField(
            model_name='basic_details',
            name='is_gold',
        ),
        migrations.RemoveField(
            model_name='basic_details',
            name='is_platinum',
        ),
        migrations.AlterField(
            model_name='basic_details',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basic_details',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='basic_details',
            name='mother_tongue',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='basic_details',
            name='religion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
